
service: s3-5min-autodelete
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.12
  region: us-west-2            # <-- change if needed
  stage: prod
  environment:
    TARGET_BUCKET: mini-fb-downloader-faisal
    DELETER_FUNCTION_NAME: ${self:service}-${sls:stage}-deleteObject
    # Pull the role ARN from this stack's CloudFormation outputs:
    #SCHEDULER_ROLE_ARN: ${cf:${self:service}-${sls:stage}.SchedulerInvokeRoleArn}
        SCHEDULER_ROLE_ARN: arn:aws:iam::${aws:accountId}:role/${self:service}-${sls:stage}-scheduler-invoke

  iam:
    role:
      statements:
        # scheduleDeleter must create schedules
        - Effect: Allow
          Action:
            - scheduler:CreateSchedule
            - scheduler:DeleteSchedule
          Resource: "*"
        # scheduleDeleter must be able to pass the invoke role to Scheduler
        - Effect: Allow
          Action: iam:PassRole
          Resource: "*" #${cf:${self:service}-${sls:stage}.SchedulerInvokeRoleArn}
        # deleteObject must delete from your bucket
        - Effect: Allow
          Action: s3:DeleteObject
          Resource:
            - arn:aws:s3:::${env:TARGET_BUCKET}/*

functions:
  scheduleDeleter:
    handler: schedule_deleter.handler
    timeout: 15
    events:
      - s3:
          bucket: ${env:TARGET_BUCKET}
          event: s3:ObjectCreated:*
          existing: true

  deleteObject:
    name: ${env:DELETER_FUNCTION_NAME}
    handler: delete_object.handler
    timeout: 15

resources:
  Resources:
    SchedulerInvokeRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${sls:stage}-scheduler-invoke
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal: { Service: scheduler.amazonaws.com }
              Action: sts:AssumeRole
        Policies:
          - PolicyName: allow-invoke-delete-object
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action: lambda:InvokeFunction
                  Resource:
                    - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${env:DELETER_FUNCTION_NAME}
                    - !Sub arn:aws:lambda:${AWS::Region}:${AWS::AccountId}:function:${env:DELETER_FUNCTION_NAME}:*

  Outputs:
    SchedulerInvokeRoleArn:
      Value: { "Fn::GetAtt": ["SchedulerInvokeRole", "Arn"] }
      Export:
        Name: ${self:service}-${sls:stage}-SchedulerInvokeRoleArn

