# .github/workflows/deploy.yml
name: Deploy to AWS (Serverless)

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  AWS_REGION: us-west-2      # <- your region
  NODE_VERSION: '20'
  SLS_DISABLE_AUTO_UPDATE: '1'   # prevent upgrade to v4 on the runner

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Serverless v3
        run: npm install -g serverless@3.39.0

      - name: Print Serverless version
        run: serverless --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Validate config
        run: serverless print --stage prod

      - name: Deploy
        run: serverless deploy --stage prod
